version: '3.8'

services:
  frontend:
    image: httpd:alpine
    container_name: pdv_frontend_apache
    ports:
      - "85:80"
    volumes:
      - ./www/frontend:/usr/local/apache2/htdocs/
      - ./logs/apache:/usr/local/apache2/logs/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./rules:/usr/local/apache2/conf/rules
    networks:
      - pdv_network
    restart: unless-stopped

  backend:
    build:
      context: ./www/backend/
      dockerfile: Dockerfile
    container_name: pdv_backend_node
    working_dir: /pdv/web
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./www/backend/src/:/pdv
      - /pdv/web/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "3005:3005"
    networks:
      - pdv_network
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./www/backend/src/web/
          target: /pdv/web
          ignore:
            - node_modules/
        - action: rebuild
          path: ./www/backend/src/web/package.json

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: pdv_cloudflared_tunnel
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    networks:
      - pdv_network
    restart: unless-stopped
    depends_on:
      - frontend
      - backend

  log_viewer:
    image: amir20/dozzle:latest
    container_name: pdv_log_viewer
    ports:
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - pdv_network
    restart: unless-stopped

networks:
  pdv_network:
    driver: bridge